name: Add mod docs to repo

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Create docs
        run: |
          ./gradlew :hmkit-fleet:dokkaGfm

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add generated docs"
          commit_user_name: "GitHub Actions"
          commit_user_email: ""
