name: Update version

on:
# disabled until we don't support v0 and v1 anymore. Read more: `./gradle/deploy-process.md`
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main

jobs:
  create-new-tag:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Create new tag
        run: ./gradlew :hmkit-fleet:release -Prelease.useAutomaticVersion=true